apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: vote
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: result
        image: benceharomi/voting-app:result
        ports:
        - containerPort: 80
      - name: postgres
        image: postgres:9.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
