apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
  namespace: voting-app
spec:
  type: LoadBalancer
  selector:
    app: result
  ports:
  - name: result
    port: 80
    targetPort: 80
  - name: postgres
    port: 5432
    targetPort: 5432