apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
  namespace: voting-app
spec:
  type: LoadBalancer
  selector:
    app: vote
  ports:
  - name: vote
    port: 80
    targetPort: 80
  - name: redis
    port: 6379
    targetPort: 6379