apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-app
  namespace: voting-app-namespace
spec:
  selector:
    app: redis-app
  ports:
  - port: 6379
    targetPort: 6379