apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-app
  namespace: voting-app-namespace
spec:
  type: LoadBalancer
  selector:
    app: result-app
  ports:
  - port: 80
    targetPort: 80
