apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote-app
  namespace: voting-app-namespace
spec:
  type: LoadBalancer
  selector:
    app: vote-app
  ports:
  - port: 80
    targetPort: 80