apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
  namespace: vote
spec:
  type: LoadBalancer
  selector:
    app: db
  ports:
  - name: result
    port: 80
    targetPort: 80
  - name: postgres
    port: 5432
    targetPort: 5432