apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: vote
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
  - name: vote
    port: 80
    targetPort: 80
  - name: redis
    port: 6379
    targetPort: 6379