apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: voting-app
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
  - name: vote
    port: 80
    targetPort: 80