apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: voting-app-namespace
  labels:
    app: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result
        image: benceharomi/voting-app:result
        ports:
        - containerPort: 80
