apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: voting-app-namespace
  labels:
    app: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote
        image: benceharomi/voting-app:vote
        ports:
        - containerPort: 80
