apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: voting-app-namespace
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker
        image: benceharomi/voting-app:worker
